{
    'name': 'vechicle repair management',
    'version': '19.0.1.1',
    'author': "cybrosys",
    'category': "service",
    'sequence': -10,
    'summary': "This is a vechicle service management module",
    'application': True,
    'installable': True,
    'auto_install': True,
    'depends': ["mail", "contacts",'account','product','fleet'],
    'data': ["security/ir.model.access.csv",
             "security/new_rc.xml",
             "data/automated_actions.xml",
             "security/record_rules.xml",
             "security/user_groups.xml",
             "data/cron_demo.xml",
             "data/email_template.xml",
             "wizards/create_vechicle_service_views.xml",
             "data/labor_product.xml",
             "views/res_partner_views.xml",
             "data/reference.xml",
             "data/demo.xml",
             "views/vehicle_tags_views.xml",
             "views/vechicle_service_views.xml",
             "views/vechicle_repair_menu.xml"]

}
